Repository AY2223S2-CS2103T-T11-1/tp, pull requests merged in 2023-03, with the labels that each got.

#48 Branch ug
  docs/AboutUs.md
  docs/UserGuide.md
Labels: documentation

#51 Update rmj1405.md with RepoSense link
  docs/team/rmj1405.md
Labels: documentation

#60 Edited Developer Guide and User Guide, added personal portfolio page
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/bisceto.md
Labels: documentation

#61 Add: Update feature to User Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#126 Feature logic help command
  build.gradle
  src/main/java/seedu/wife/commons/core/HelpMenu.java
  src/main/java/seedu/wife/logic/commands/CommandResult.java
  src/main/java/seedu/wife/logic/commands/generalcommands/ExitCommand.java
  src/main/java/seedu/wife/logic/commands/generalcommands/HelpCommand.java
  src/main/java/seedu/wife/logic/parser/HelpCommandParser.java
  src/main/java/seedu/wife/logic/parser/WifeParser.java
  src/main/java/seedu/wife/ui/HelpWindow.java
  src/main/java/seedu/wife/ui/MainWindow.java
  src/main/java/seedu/wife/ui/PersonCard.java
  src/main/java/seedu/wife/ui/PersonListPanel.java
  src/test/java/seedu/wife/commons/core/HelpMenuTest.java
  src/test/java/seedu/wife/logic/commands/CommandResultTest.java
  src/test/java/seedu/wife/logic/commands/generalcommands/ExitCommandTest.java
  src/test/java/seedu/wife/logic/commands/generalcommands/HelpCommandTest.java
  src/test/java/seedu/wife/logic/parser/HelpCommandParserTest.java
Labels: feature

#129 Add test for `TagFoodCommand` and `TagFoodCommandParser`
  src/main/java/seedu/wife/commons/core/Messages.java
  src/main/java/seedu/wife/commons/util/StringUtil.java
  src/main/java/seedu/wife/logic/commands/tagcommands/CreateTagCommand.java
  src/main/java/seedu/wife/logic/commands/tagcommands/TagFoodCommand.java
  src/main/java/seedu/wife/logic/parser/tagcommandparser/TagFoodCommandParser.java
  src/main/java/seedu/wife/model/food/Food.java
  src/test/java/seedu/wife/logic/commands/CommandTestUtil.java
  src/test/java/seedu/wife/logic/commands/foodcommands/AddCommandIntegrationTest.java
  src/test/java/seedu/wife/logic/commands/foodcommands/DeleteCommandTest.java
  src/test/java/seedu/wife/logic/commands/foodcommands/EditCommandTest.java
  src/test/java/seedu/wife/logic/commands/foodcommands/FindCommandTest.java
  src/test/java/seedu/wife/logic/commands/foodcommands/ListCommandTest.java
  src/test/java/seedu/wife/logic/commands/generalcommands/ClearCommandTest.java
  src/test/java/seedu/wife/logic/commands/tagcommands/CreateTagCommandTest.java
  src/test/java/seedu/wife/logic/commands/tagcommands/TagFoodCommandTest.java
  src/test/java/seedu/wife/logic/parser/ParserUtilTest.java
  src/test/java/seedu/wife/logic/parser/WifeParserTest.java
  src/test/java/seedu/wife/logic/parser/foodcommandparser/DeleteCommandParserTest.java
  src/test/java/seedu/wife/logic/parser/foodcommandparser/EditCommandParserTest.java
  src/test/java/seedu/wife/logic/parser/tagcommandparser/TagFoodCommandParserTest.java
  src/test/java/seedu/wife/model/WifeTest.java
  src/test/java/seedu/wife/testutil/TypicalFood.java
  src/test/java/seedu/wife/testutil/TypicalIndex.java
  src/test/java/seedu/wife/testutil/TypicalTag.java
  src/test/java/seedu/wife/testutil/TypicalWife.java
Labels: priority.HIGH

#164 Documentation feature help untag UG+DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/wife/HelpCommandActivityDiagram.puml
  docs/images/HelpCommandActivityDiagram.png
Labels: documentation

#166 DG: Draft Write Up on AddFood, EditFood and TagFood
  docs/DeveloperGuide.md
Labels: documentation

#172 UG: Add createtag and screenshots to display result
  docs/UserGuide.md
  docs/images/UG/AddFood.png
  docs/images/UG/DeleteFood.png
  docs/images/UG/TagFood.png
  docs/images/UG/UntagFood.png
Labels: documentation
